apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels: 
    app: myjavaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjavaapp
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: myjavaapp
    spec:
      containers:
      - name: mycon
        image: maha4iac/mahaonlinestore:1
        ports:
        - containerPort: 8080
