apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
    app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: nginx-container
          image: maha4iac/mahaonlinestore:2
          ports:
            - containerPort: 8080
