apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: mynginx
spec:
  type: NodePort
  ports:
  - name: svc
    protocol: TCP
    port: 80
    nodePort: 30001
  selector:
    app: mynginx
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  